### ISSUE TITLE
Post merge issue of PR #48

### ISSUE THREAD

**Issue by asroy** [asroy/composable_kernel#50]
https://github.com/asroy/composable_kernel/pull/48#discussion_r671606621
https://github.com/asroy/composable_kernel/pull/48#discussion_r671606712

BlockwiseGemmXdlops_km_kn_m0m1m2n_v1
BlockwiseGemmXdlops_km_kn_m0m1m2n_v1_2x2pipeline 
need to be renamed to correctly reflect the dimensions

**Comment by aserio** [comment]
Closed with https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/13
